; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
upload_protocol = custom
upload_port = router@<pi-ip>
upload_command = scp .pio/build/rpipico2/firmware.bin router@10.42.0.1:~/firmware.bin && ssh router@<pi-ip> "picotool load ~/firmware.bin -f && picotool reboot"

build_flags = 
    -D PICO_W
    -Wno-error=unused-variable

build_unflags = 
    -Werror